apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
  labels:
    student: {{ .Values.studentName }}
data:
  index.html: |
    {{- .Values.configMap.index | nindent 4 }}