apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- range $key, $value := .Values.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
      
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector: 
    matchLabels:
      {{- range $key, $value := .Values.labels }}
      {{ $key }}: {{ $value }}
      {{- end }}
  template:
    metadata:
      labels: 
        {{- range $key, $value := .Values.labels }}
        {{ $key }}: {{ $value }}
        {{- end }}
    spec: 
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: {{ .Values.deployment.containerName }}
        image: {{ .Values.deployment.imageName }}:{{ .Values.deployment.imageVersion }}
        ports: 
          - containerPort: {{ .Values.deployment.containerPort }}
        volumeMounts:
          - name: html-content
            mountPath: /usr/share/nginx/html/index.html
            subPath: index.html
      volumes:
        - name: html-content
          configMap:
            name: {{ .Values.configMap.name }}


